Resources:
  MyInstance:
      Type: AWS::EC2::Instance
      Properties:
        ImageId: ami-02e136e904f3da870
        InstanceType: t2.micro
        Tags:
          - Key: "Name"
            Value: "exmaple"
        SecurityGroups:
          - !Ref VprofileSG

  VprofileSG:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Allow SSH and httpd
        SecurityGroupIngress:
          - IpProtocol: TCP 
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: TCP 
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
        Tags:
          - Key: "Name"
            Value: "VprofileSGTag"