AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  myKeyPair: 
    Description: Amazon EC2 Key Pair
    Type: "AWS::EC2::KeyPair::KeyName"

  AZ: 
    Description: AZs
    Type: "AWS::EC2::AvailabilityZone::Name"

  InstanceTypeParameterSSM: 
    Type: 'AWS::SSM::Parameter::Value<String>'

  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.

Resources:
  DevEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-04902260ca3d33422"
      AvailabilityZone: !Ref AZ
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref myKeyPair
      SecurityGroups:
        - default



