AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  Environment:
    Description: Choose environment dev or prod
    Type: String
    AllowedValues: ['dev','prod']
Conditions:
  CreateProdSecurityGroup: !Equals [!Ref Environment, 'prod' ]
  CreateDevSecurityGroup: !Not [Condition: CreateProdSecurityGroup]

Resources: 
  myEC2Instance: 
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: ami-0ff8a91507f77f867
      InstanceType: t2.micro
      SecurityGroupIds: !If [CreateProdSecurityGroup, [!Ref MyProdSecGroup],[!Ref MyDevSecGroup]]

  MyProdSecGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateProdSecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  MyDevSecGroup:
    Type: AWS::EC2::SecurityGroup
    Condition: CreateDevSecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0