Parameters:
  ImageID:
      Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
      Description: TCP/IP port for the database
      Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>


Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageID
      InstanceType: "t2-micro"
    DependsOn:
      MyS3Bucket

  MyS3Bucket:
    Type: AWS::S3::Bucket