Resources:
    MyEC2Instance: 
      Type: AWS::EC2::Instance
      Properties: 
        ImageId: "ami-02e136e904f3da870"
        AvailabilityZone: us-east-1a
        InstanceType: t2.micro
        SecurityGroups: 
          - !Ref SSHSecurityGroup
          - !Ref ServerSecurityGroup

    MyEIP:
      Type: AWS::EC2::EIP
      Properties: 
        InstanceId: !Ref MyEC2Instance


    SSHSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          GroupDescription: Allow http to client host
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0


    ServerSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
          GroupDescription: Allow http to client host
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
