Parameters:
  BucketName:
    Description: Bucket-name
    Type: String
    Default: "yoga.ml-bucket"

Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref BucketName
    DeletionPolicy: Retain 
    UpdateReplacePolicy: Retain 
